### ISSUE TITLE
Browser doesn't show h3 protocol

### ISSUE THREAD

**Issue by pako88** [RanadeepPolavarapu/docker-nginx-http3#31]
Hello,

i set up a website with this docker container as base image. everythings working fine so far. Except that somehow all browsers are still connecting with http2 (tested with latest chrome and latest firefox - http3 is enabled in all browsers - this was verified on https://quic.nginx.org/).  
https://www.http3check.net/ and curl with forced http3 are showing that my website is correctly set up with http3.
i also created a separate example with caddy and there the browsers are showing http3 correctly.

is this a known "issue" of this project? 

Thanks

**Comment by der--flo** [comment]
Same here, it is working when forced, but not in the Browser:

**Comment by RanadeepPolavarapu** [comment]
@pako88 @der--flo Please try with latest image.

**Comment by der--flo** [comment]
No luck for me. 

btw. your readme tells "Alpine Linux image with nginx 1.19.5 (mainline) ", but in the Dockerfile you use "ENV NGINX_VERSION 1.16.1"

**Comment by RanadeepPolavarapu** [comment]
@der--flo the quiche H3 doesn't work with nginx 1.19.5. I have moved nginx to the latest supported version which is `1.16.1`. H3 should be working now and I see your latest edit now saying it is working for you.

**Comment by pako88** [comment]
still no luck for me.
Latest version in repository and changes from @der--flo are both not working for me

**Comment by RanadeepPolavarapu** [comment]
Please try again with this header in 8ef7b85597ca3b2d2127352c746c3fe041450185.

**Comment by vadymmasiuk** [comment]
I have exactly same problem.
It works well with cURL, but not with browsers...
So, any solution?

**Comment by RanadeepPolavarapu** [comment]
With 8ef7b85597ca3b2d2127352c746c3fe041450185 applied in your nginx conf it is still failing?

**Comment by vadymmasiuk** [comment]
> With [8ef7b85](https://github.com/RanadeepPolavarapu/docker-nginx-http3/commit/8ef7b85597ca3b2d2127352c746c3fe041450185) applied in your nginx conf it is still failing?

Yes
Anyway I have changed little bit to get it working:
add_header alt-svc 'h3=":443"; ma=600,h3-29=":443"; ma=600,h2=":443"; ma=600,quic=":443"; ma=600; v="46,43"';

seems like h3-27 and 28 are not supported with latest Chromium-based releases

**Comment by steklopod** [comment]
> > With [8ef7b85](https://github.com/RanadeepPolavarapu/docker-nginx-http3/commit/8ef7b85597ca3b2d2127352c746c3fe041450185) applied in your nginx conf it is still failing?
> 
> Yes Anyway I have changed little bit to get it working: add_header alt-svc 'h3=":443"; ma=600,h3-29=":443"; ma=600,h2=":443"; ma=600,quic=":443"; ma=600; v="46,43"';
> 
> seems like h3-27 and 28 are not supported anymore with latest Chromium-based releases

Didn't help 💁🏻
